repos:
- repo: https://github.com/psf/black
  rev: 24.10.0
  hooks:
  - id: black
    args:
    - "--line-length=88"
    #language_version: python3.10
    stages: [pre-commit]

- repo: https://github.com/pycqa/flake8
  rev: 7.1.1
  hooks:
  - id: flake8
    args:
    - "--max-line-length=88"
    - "--docstring-convention=numpy"
    name: flake8
    additional_dependencies: [
      "flake8-docstrings"
    ]
    stages: [pre-commit]

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.11.2
  hooks:
  - id: mypy
    stages: [pre-commit]

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: trailing-whitespace
    stages: [pre-commit]
  - id: end-of-file-fixer
    stages: [pre-commit]
  - id: check-added-large-files
    stages: [pre-commit]
    args:
    - "--maxkb=10000"

# python -m pytest
- repo: local
  hooks:
  - id: run-pytest
    name: pytest
    entry: python
    args:
      - -m
      - pytest
    language: system
    pass_filenames: false
    stages: [pre-commit]

  - id: run-pytest-with-coverage
    name: pytest-coverage
    entry: bash
    args:
      - '-c'
      - |
        coverage run -m pytest
        python -m pytest --cov=. --cov-report=html:docs/source/_static/coverage
        coverage-badge -f -o docs/source/_static/coverage-badge.svg
    language: system
    pass_filenames: false
    stages: [pre-commit]

  - id: build documentation
    name: build-docs
    entry: bash
    args:
      - '-c'
      - |
        sphinx-apidoc consumer --output-dir docs/source --force --separate --no-toc --implicit-namespaces && sphinx-build docs/source docs/build
    language: system